name: Run Build Application on Pull Request
on:
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    name: Angular Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Installing Angular CLI
        run: yarn global add @angular/cli

      - name: Installing dependencies
        run: yarn --frozen-lockfile

      - name: Build a SPA Angular Application
        run: yarn build
